# This workflow will run other workflows
name: Build (All)

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu:
    uses: ./.github/workflows/build_sview_ubuntu.yml
  android-ffmpeg:
    uses: ./.github/workflows/build_sview_android_ffmpeg.yml
  android:
    needs: [android-ffmpeg]
    uses: ./.github/workflows/build_sview_android.yml
  macos-ffmpeg:
    uses: ./.github/workflows/build_sview_macos_ffmpeg.yml
  macos:
    needs: [macos-ffmpeg]
    uses: ./.github/workflows/build_sview_macos.yml
  mingw-ffmpeg:
    uses: ./.github/workflows/build_sview_mingw_ffmpeg.yml
  mingw:
    needs: [mingw-ffmpeg]
    uses: ./.github/workflows/build_sview_mingw.yml
  windows:
    needs: [mingw-ffmpeg]
    uses: ./.github/workflows/build_sview_windows.yml
