# This workflow will run other workflows
name: Build (All)

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux-gcc:
    uses: ./.github/workflows/build_sview_linux_gcc.yml
  linux-android-ffmpeg:
    uses: ./.github/workflows/build_sview_linux_android_ffmpeg.yml
  linux-android:
    needs: [linux-android-ffmpeg]
    uses: ./.github/workflows/build_sview_linux_android.yml
  macos-clang-ffmpeg:
    uses: ./.github/workflows/build_sview_macos_clang_ffmpeg.yml
  macos-clang:
    needs: [macos-clang-ffmpeg]
    uses: ./.github/workflows/build_sview_macos_clang.yml
  linux-mingw-ffmpeg:
    uses: ./.github/workflows/build_sview_linux_mingw_ffmpeg.yml
  linux-mingw:
    needs: [linux-mingw-ffmpeg]
    uses: ./.github/workflows/build_sview_linux_mingw.yml
  windows-msvc:
    needs: [linux-mingw-ffmpeg]
    uses: ./.github/workflows/build_sview_windows_msvc.yml
