name: Build (Ubuntu)
on:
  workflow_call:

jobs:
  # build sView on Linux using standard toolchain (e.g. gcc)
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Clone Tree
      uses: actions/checkout@v6
      with:
        path: sview.git
        fetch-depth: 1
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          g++ ninja-build \
          zenity \
          libopenal-dev \
          libopenvr-dev \
          libgl-dev \
          libfreetype-dev libfontconfig-dev \
          libconfig++-dev libconfig-dev \
          libxrandr-dev libxpm-dev \
          libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev libswscale-dev
    - name: Configure project
      env:
        SVIEW_CONFIG: |
          set(USE_OPENVR    ON CACHE BOOL "")
          set(USE_MONGOOSE  ON CACHE BOOL "")
          set(USE_UPDATER  OFF CACHE BOOL "")
          set(USE_STCONFIG OFF CACHE BOOL "")
          set(BUILD_TREAT_WARNINGS_AS_ERRORS ON CACHE BOOL "")
          set(CMAKE_INSTALL_PREFIX "${CMAKE_CURRENT_LIST_DIR}/sview-install" CACHE PATH "")
      run: |
        echo "${SVIEW_CONFIG}" | tee ./sview-make.cmake
        cmake -S ./sview.git -B ./sview-make -G Ninja --toolchain "$PWD/sview-make.cmake"
    - name: Build project
      run: |
        cmake --build ./sview-make
    - name: Install project
      run: |
        cmake --install ./sview-make --prefix ./sview-install
    - name: Install Dependencies for Testing
      run: |
        sudo apt-get install -y \
          xvfb scrot
    - name: Run StMonitorsDump
      run: |
        export LD_LIBRARY_PATH=$PWD/sview-install/lib
        xvfb-run -a --server-args="-screen 0 1920x1080x24" \
          ./sview-install/bin/StMonitorsDump --nohtml
    - name: Run StMoviePlayer
      run: |
        export LD_LIBRARY_PATH=$PWD/sview-install/lib
        xvfb-run -a --server-args="-screen 0 1920x1080x24" bash \
          ./sview.git/adm/ci/screenshot.sh ./sview-install/sview-player-linux.png 5 \
          ./sview-install/bin/sView --windowLeft=100 --windowTop=100
    - name: Run StImageViewer
      run: |
        export LD_LIBRARY_PATH=$PWD/sview-install/lib
        xvfb-run -a --server-args="-screen 0 1920x1080x24" bash \
          ./sview.git/adm/ci/screenshot.sh ./sview-install/sview-viewer-linux.png 2 \
          ./sview-install/bin/sView ./sview.git/share/sView/demo/demo.jps
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sview-${{ matrix.os }}-screenshots
        path: ./sview-install/*.png
        if-no-files-found: error

  # build source package in Debian format for Ubuntu
  debpkg:
    strategy:
      matrix:
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Clone Tree
      uses: actions/checkout@v6
      with:
        path: sview.git
        fetch-depth: 1
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential debhelper devscripts cmake ninja-build \
          libopenal-dev \
          libopenvr-dev \
          libgl-dev \
          libfreetype-dev libfontconfig-dev \
          libconfig++-dev libconfig-dev \
          libxrandr-dev libxpm-dev \
          libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev libswscale-dev
    - name: Build
      run: |
        bash ./sview.git/distribution/buildDebSrc.sh

  # the job performing build for Android using old dependencies
  build-android-fastcheck:
    runs-on: ubuntu-24.04
    steps:
    - name: Clone Tree
      uses: actions/checkout@v6
      with:
        path: sview.git
        fetch-depth: 1
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          ninja-build
    - name: Compile
      run: |
        ./sview.git/adm/ci/build_sview_android.sh
    #- name: Upload artifacts
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: sview-apk-old
    #    path: sview.git/build/sView-Release.apk
    #    if-no-files-found: error
    #    compression-level: 0

  # the job performing build for macOS using Homebrew dependencies
  build-macos-brew:
    runs-on: macos-15
    steps:
    - name: Clone Tree
      uses: actions/checkout@v6
      with:
        path: sview.git
        fetch-depth: 1
    - name: Install Dependencies
      run: |
        brew update
        brew install \
          freetype \
          ffmpeg \
          openal-soft
    - name: Compile
      run: |
        ./sview.git/adm/ci/build_sview_osx.sh
    - name: Run StMonitorsDump
      run: |
        ./sview.git/build/Release.app/Contents/MacOS/StMonitorsDump --nohtml
