name: Build (Ubuntu)
on:
  workflow_call:

jobs:
  build-ubuntu-24-04:
    runs-on: ubuntu-24.04
    steps:
    - name: Clone Tree
      uses: actions/checkout@v6
      with:
        path: sview.git
        fetch-depth: 1
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          g++ ninja-build \
          zenity \
          libopenal-dev \
          libopenvr-dev \
          libgl-dev \
          libfreetype-dev libfontconfig-dev \
          libconfig++-dev libconfig-dev \
          libxrandr-dev libxpm-dev \
          libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev libswscale-dev
    - name: Build
      run: |
        bash ./sview.git/adm/ci/build_sview_linux.sh
    - name: Install Dependencies for Testing
      run: |
        sudo apt-get install -y \
          xvfb scrot
    - name: Run tests
      run: |
        export LD_LIBRARY_PATH=$PWD/sview.git/build/install/lib
        xvfb-run --server-args="-screen 0 1920x1080x24" bash \
          ./sview.git/adm/ci/screenshot.sh ./sview.git/build/sview-player-linux.png 5 \
          ./sview.git/build/install/bin/sView --windowLeft=100 --windowTop=100
        xvfb-run --server-args="-screen 0 1920x1080x24" bash \
          ./sview.git/adm/ci/screenshot.sh ./sview.git/build/sview-viewer-linux.png 2 \
          ./sview.git/build/install/bin/sView ./sview.git/share/sView/demo/demo.jps
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sview-linux-screenshots
        path: ./sview.git/build/*.png
        if-no-files-found: error

  build-ubuntu-24-04-debpkg:
    runs-on: ubuntu-24.04
    steps:
    - name: Clone Tree
      uses: actions/checkout@v6
      with:
        path: sview.git
        fetch-depth: 1
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential debhelper devscripts cmake ninja-build \
          libopenal-dev \
          libopenvr-dev \
          libgl-dev \
          libfreetype-dev libfontconfig-dev \
          libconfig++-dev libconfig-dev \
          libxrandr-dev libxpm-dev \
          libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev libswscale-dev
    - name: Build
      run: |
        bash ./sview.git/distribution/buildDebSrc.sh

  build-ubuntu-22-04:
    runs-on: ubuntu-22.04
    steps:
    - name: Clone Tree
      uses: actions/checkout@v6
      with:
        path: sview.git
        fetch-depth: 1
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          g++ ninja-build \
          libopenal-dev \
          libopenvr-dev \
          libgl-dev \
          libfreetype-dev libfontconfig-dev \
          libconfig++-dev libconfig-dev \
          libxrandr-dev libxpm-dev \
          libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev libswscale-dev
    - name: Build
      run: |
        ./sview.git/adm/ci/build_sview_linux.sh
