name: Build (Linux/GCC)
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-ubuntu-24-04:
    runs-on: ubuntu-24.04
    steps:
    - name: Clone Tree
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          g++ ninja-build \
          zenity \
          libopenal-dev \
          libopenvr-dev \
          libgl-dev \
          libfreetype-dev libfontconfig-dev \
          libconfig++-dev libconfig-dev \
          libxrandr-dev libxpm-dev \
          libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev libswscale-dev
    - name: Compile
      run: |
        bash ./adm/ci/build_sview_linux.sh
    - name: Extra Dependencies
      run: |
        sudo apt-get install -y \
          build-essential debhelper devscripts cmake
    - name: Debian package
      run: |
        bash ./distribution/buildDebSrc.sh
    #- name: Upload artifacts
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: sview-debpackage
    #    path: distribution/temp

  build-ubuntu-22-04:
    runs-on: ubuntu-22.04
    steps:
    - name: Clone Tree
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          g++ ninja-build \
          libopenal-dev \
          libopenvr-dev \
          libgl-dev \
          libfreetype-dev libfontconfig-dev \
          libconfig++-dev libconfig-dev \
          libxrandr-dev libxpm-dev \
          libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev libswscale-dev
    - name: Compile
      run: |
        ./adm/ci/build_sview_linux.sh
