name: Build (Linux/GCC)
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-ubuntu-24-04:
    runs-on: ubuntu-24.04
    steps:
    - name: Clone Tree
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          g++ ninja-build \
          zenity \
          libopenal-dev \
          libopenvr-dev \
          libgl-dev \
          libfreetype-dev libfontconfig-dev \
          libconfig++-dev libconfig-dev \
          libxrandr-dev libxpm-dev \
          libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev libswscale-dev
    - name: Compile
      run: |
        bash ./adm/ci/build_sview_linux.sh
    - name: Install Dependencies for Testing
      run: |
        sudo apt-get install -y \
          xvfb scrot
    - name: Run tests
      run: |
        LD_LIBRARY_PATH=$PWD/build/install/lib xvfb-run --server-args="-screen 0 1920x1080x24" bash \
          ./adm/ci/screenshot.sh ./build/sview-player-linux.png 5 \
          ./build/install/bin/sView --windowLeft=100 --windowTop=100
        LD_LIBRARY_PATH=$PWD/build/install/lib xvfb-run --server-args="-screen 0 1920x1080x24" bash \
          ./adm/ci/screenshot.sh ./build/sview-viewer-linux.png 2 \
          ./build/install/bin/sView ./share/sView/demo/demo.jps
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sview-linux-screenshots
        path: ./build/*.png
    - name: Install Dependencies for Debian Package Helper
      run: |
        sudo apt-get install -y \
          build-essential debhelper devscripts cmake
    - name: Debian package
      run: |
        bash ./distribution/buildDebSrc.sh

  build-ubuntu-22-04:
    runs-on: ubuntu-22.04
    steps:
    - name: Clone Tree
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          g++ ninja-build \
          libopenal-dev \
          libopenvr-dev \
          libgl-dev \
          libfreetype-dev libfontconfig-dev \
          libconfig++-dev libconfig-dev \
          libxrandr-dev libxpm-dev \
          libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev libswscale-dev
    - name: Compile
      run: |
        ./adm/ci/build_sview_linux.sh
